name: ece501-final
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas
  - pyarrow
  - numpy
  - matplotlib
  - tabulate
  - requests
  - beautifulsoup4
  - tqdm
  - pip:
      - chardet  # helps with file encoding edge-cases on Windows