execution_config:
  runs_per_query: 30
  timeout_seconds: 30
  queries_to_run:
    - baseline_query2
  dataset_partitions_per_query:
    baseline_query1:
      - 10000
      - 50000
      - 100000
      # - 500000
    baseline_query2:
      - 10000
      - 50000
      - 100000
      - 500000
    baseline_query3:
      - 10000
      - 50000
      - 100000
      - 500000