execution_config:
  runs_per_query: 5
  timeout_seconds: 30
  queries_to_run:
    - baseline_query2
  dataset_partitions_per_query:
    baseline_query1:
      - 10000
      - 50000
      - 100000
      - 200000
      - 300000
      - 400000
      - 500000
    baseline_query2:
      - 1000
      - 2000
      - 5000
      - 10000
      - 20000
      - 50000
      - 100000
      - 200000
      - 300000
    baseline_query3:
      - 1000
      - 2000
      - 5000
      - 10000
      - 20000
      - 50000
      - 100000
      - 200000
      - 300000
    star_query1:
      - 10000
      - 50000
      - 100000
      - 200000
      - 300000
      - 400000
    star_query2:
      - 1000
      - 2000
      - 5000
      - 10000
      - 20000
      - 50000
      - 100000
      - 200000
      - 300000
    star_query3:
      - 1000
      - 2000
      - 5000
      - 10000
      - 20000
      - 50000
      - 100000
      - 200000
      - 300000