query_config:
  baseline_query1:
    execute: true
    sql_file: "sql/baseline_query1.sql"
    num_runs: 5
    timeout: 300  # seconds
    version: "1.0"
  baseline_query2:
    execute: false
    sql_file: "sql/baseline_query2.sql"
    num_runs: 5
    timeout: 300  # seconds
    version: "1.0"
  baseline_query3:
    execute: false
    sql_file: "sql/baseline_query3.sql"
    num_runs: 5
    timeout: 300  # seconds
    version: "1.0"
  designed_query1:
    execute: false
    sql_file: "sql/designed_query1.sql"
    num_runs: 5
    timeout: 300  # seconds
    version: "1.0"
  designed_query2:
    execute: false
    sql_file: "sql/designed_query2.sql"
    num_runs: 5
    timeout: 300  # seconds
    version: "1.0"
  designed_query3:
    execute: true
    sql_file: "sql/designed_query3.sql"
    num_runs: 5
    timeout: 300  # seconds
    version: "1.0"